var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
import { IsString, IsNotEmpty, IsOptional, IsUrl, IsBoolean, IsNumber, IsEnum, IsDateString, IsEmail } from 'class-validator';
import { MemberStatus, MemberAccess } from '@/entities/team-member.entity';
let CreateTeamMemberDto = (() => {
    let _name_decorators;
    let _name_initializers = [];
    let _name_extraInitializers = [];
    let _role_decorators;
    let _role_initializers = [];
    let _role_extraInitializers = [];
    let _department_decorators;
    let _department_initializers = [];
    let _department_extraInitializers = [];
    let _departmentId_decorators;
    let _departmentId_initializers = [];
    let _departmentId_extraInitializers = [];
    let _email_decorators;
    let _email_initializers = [];
    let _email_extraInitializers = [];
    let _phone_decorators;
    let _phone_initializers = [];
    let _phone_extraInitializers = [];
    let _access_decorators;
    let _access_initializers = [];
    let _access_extraInitializers = [];
    let _status_decorators;
    let _status_initializers = [];
    let _status_extraInitializers = [];
    let _joinDate_decorators;
    let _joinDate_initializers = [];
    let _joinDate_extraInitializers = [];
    let _avatarInitials_decorators;
    let _avatarInitials_initializers = [];
    let _avatarInitials_extraInitializers = [];
    let _avatarColor_decorators;
    let _avatarColor_initializers = [];
    let _avatarColor_extraInitializers = [];
    let _bio_decorators;
    let _bio_initializers = [];
    let _bio_extraInitializers = [];
    let _photoUrl_decorators;
    let _photoUrl_initializers = [];
    let _photoUrl_extraInitializers = [];
    let _photo_decorators;
    let _photo_initializers = [];
    let _photo_extraInitializers = [];
    let _linkedinUrl_decorators;
    let _linkedinUrl_initializers = [];
    let _linkedinUrl_extraInitializers = [];
    let _order_decorators;
    let _order_initializers = [];
    let _order_extraInitializers = [];
    let _activityCount_decorators;
    let _activityCount_initializers = [];
    let _activityCount_extraInitializers = [];
    let _isActive_decorators;
    let _isActive_initializers = [];
    let _isActive_extraInitializers = [];
    return class CreateTeamMemberDto {
        static {
            const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
            _name_decorators = [IsString(), IsNotEmpty({ message: 'Le nom est requis' })];
            _role_decorators = [IsString(), IsNotEmpty({ message: 'Le rôle est requis' })];
            _department_decorators = [IsOptional(), IsString()];
            _departmentId_decorators = [IsOptional(), IsString()];
            _email_decorators = [IsOptional(), IsEmail({}, { message: 'Adresse email invalide' })];
            _phone_decorators = [IsOptional(), IsString()];
            _access_decorators = [IsOptional(), IsEnum(MemberAccess)];
            _status_decorators = [IsOptional(), IsEnum(MemberStatus)];
            _joinDate_decorators = [IsOptional(), IsDateString()];
            _avatarInitials_decorators = [IsOptional(), IsString()];
            _avatarColor_decorators = [IsOptional(), IsString()];
            _bio_decorators = [IsOptional(), IsString()];
            _photoUrl_decorators = [IsOptional(), IsString()];
            _photo_decorators = [IsOptional(), IsString()];
            _linkedinUrl_decorators = [IsOptional(), IsUrl({}, { message: 'URL LinkedIn invalide' })];
            _order_decorators = [IsOptional(), IsNumber()];
            _activityCount_decorators = [IsOptional(), IsNumber()];
            _isActive_decorators = [IsOptional(), IsBoolean()];
            __esDecorate(null, null, _name_decorators, { kind: "field", name: "name", static: false, private: false, access: { has: obj => "name" in obj, get: obj => obj.name, set: (obj, value) => { obj.name = value; } }, metadata: _metadata }, _name_initializers, _name_extraInitializers);
            __esDecorate(null, null, _role_decorators, { kind: "field", name: "role", static: false, private: false, access: { has: obj => "role" in obj, get: obj => obj.role, set: (obj, value) => { obj.role = value; } }, metadata: _metadata }, _role_initializers, _role_extraInitializers);
            __esDecorate(null, null, _department_decorators, { kind: "field", name: "department", static: false, private: false, access: { has: obj => "department" in obj, get: obj => obj.department, set: (obj, value) => { obj.department = value; } }, metadata: _metadata }, _department_initializers, _department_extraInitializers);
            __esDecorate(null, null, _departmentId_decorators, { kind: "field", name: "departmentId", static: false, private: false, access: { has: obj => "departmentId" in obj, get: obj => obj.departmentId, set: (obj, value) => { obj.departmentId = value; } }, metadata: _metadata }, _departmentId_initializers, _departmentId_extraInitializers);
            __esDecorate(null, null, _email_decorators, { kind: "field", name: "email", static: false, private: false, access: { has: obj => "email" in obj, get: obj => obj.email, set: (obj, value) => { obj.email = value; } }, metadata: _metadata }, _email_initializers, _email_extraInitializers);
            __esDecorate(null, null, _phone_decorators, { kind: "field", name: "phone", static: false, private: false, access: { has: obj => "phone" in obj, get: obj => obj.phone, set: (obj, value) => { obj.phone = value; } }, metadata: _metadata }, _phone_initializers, _phone_extraInitializers);
            __esDecorate(null, null, _access_decorators, { kind: "field", name: "access", static: false, private: false, access: { has: obj => "access" in obj, get: obj => obj.access, set: (obj, value) => { obj.access = value; } }, metadata: _metadata }, _access_initializers, _access_extraInitializers);
            __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: obj => "status" in obj, get: obj => obj.status, set: (obj, value) => { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
            __esDecorate(null, null, _joinDate_decorators, { kind: "field", name: "joinDate", static: false, private: false, access: { has: obj => "joinDate" in obj, get: obj => obj.joinDate, set: (obj, value) => { obj.joinDate = value; } }, metadata: _metadata }, _joinDate_initializers, _joinDate_extraInitializers);
            __esDecorate(null, null, _avatarInitials_decorators, { kind: "field", name: "avatarInitials", static: false, private: false, access: { has: obj => "avatarInitials" in obj, get: obj => obj.avatarInitials, set: (obj, value) => { obj.avatarInitials = value; } }, metadata: _metadata }, _avatarInitials_initializers, _avatarInitials_extraInitializers);
            __esDecorate(null, null, _avatarColor_decorators, { kind: "field", name: "avatarColor", static: false, private: false, access: { has: obj => "avatarColor" in obj, get: obj => obj.avatarColor, set: (obj, value) => { obj.avatarColor = value; } }, metadata: _metadata }, _avatarColor_initializers, _avatarColor_extraInitializers);
            __esDecorate(null, null, _bio_decorators, { kind: "field", name: "bio", static: false, private: false, access: { has: obj => "bio" in obj, get: obj => obj.bio, set: (obj, value) => { obj.bio = value; } }, metadata: _metadata }, _bio_initializers, _bio_extraInitializers);
            __esDecorate(null, null, _photoUrl_decorators, { kind: "field", name: "photoUrl", static: false, private: false, access: { has: obj => "photoUrl" in obj, get: obj => obj.photoUrl, set: (obj, value) => { obj.photoUrl = value; } }, metadata: _metadata }, _photoUrl_initializers, _photoUrl_extraInitializers);
            __esDecorate(null, null, _photo_decorators, { kind: "field", name: "photo", static: false, private: false, access: { has: obj => "photo" in obj, get: obj => obj.photo, set: (obj, value) => { obj.photo = value; } }, metadata: _metadata }, _photo_initializers, _photo_extraInitializers);
            __esDecorate(null, null, _linkedinUrl_decorators, { kind: "field", name: "linkedinUrl", static: false, private: false, access: { has: obj => "linkedinUrl" in obj, get: obj => obj.linkedinUrl, set: (obj, value) => { obj.linkedinUrl = value; } }, metadata: _metadata }, _linkedinUrl_initializers, _linkedinUrl_extraInitializers);
            __esDecorate(null, null, _order_decorators, { kind: "field", name: "order", static: false, private: false, access: { has: obj => "order" in obj, get: obj => obj.order, set: (obj, value) => { obj.order = value; } }, metadata: _metadata }, _order_initializers, _order_extraInitializers);
            __esDecorate(null, null, _activityCount_decorators, { kind: "field", name: "activityCount", static: false, private: false, access: { has: obj => "activityCount" in obj, get: obj => obj.activityCount, set: (obj, value) => { obj.activityCount = value; } }, metadata: _metadata }, _activityCount_initializers, _activityCount_extraInitializers);
            __esDecorate(null, null, _isActive_decorators, { kind: "field", name: "isActive", static: false, private: false, access: { has: obj => "isActive" in obj, get: obj => obj.isActive, set: (obj, value) => { obj.isActive = value; } }, metadata: _metadata }, _isActive_initializers, _isActive_extraInitializers);
            if (_metadata) Object.defineProperty(this, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        }
        name = __runInitializers(this, _name_initializers, void 0);
        role = (__runInitializers(this, _name_extraInitializers), __runInitializers(this, _role_initializers, void 0));
        department = (__runInitializers(this, _role_extraInitializers), __runInitializers(this, _department_initializers, void 0));
        departmentId = (__runInitializers(this, _department_extraInitializers), __runInitializers(this, _departmentId_initializers, void 0));
        email = (__runInitializers(this, _departmentId_extraInitializers), __runInitializers(this, _email_initializers, void 0));
        phone = (__runInitializers(this, _email_extraInitializers), __runInitializers(this, _phone_initializers, void 0));
        access = (__runInitializers(this, _phone_extraInitializers), __runInitializers(this, _access_initializers, void 0));
        status = (__runInitializers(this, _access_extraInitializers), __runInitializers(this, _status_initializers, void 0));
        joinDate = (__runInitializers(this, _status_extraInitializers), __runInitializers(this, _joinDate_initializers, void 0));
        avatarInitials = (__runInitializers(this, _joinDate_extraInitializers), __runInitializers(this, _avatarInitials_initializers, void 0));
        avatarColor = (__runInitializers(this, _avatarInitials_extraInitializers), __runInitializers(this, _avatarColor_initializers, void 0));
        bio = (__runInitializers(this, _avatarColor_extraInitializers), __runInitializers(this, _bio_initializers, void 0));
        photoUrl = (__runInitializers(this, _bio_extraInitializers), __runInitializers(this, _photoUrl_initializers, void 0));
        photo = (__runInitializers(this, _photoUrl_extraInitializers), __runInitializers(this, _photo_initializers, void 0));
        linkedinUrl = (__runInitializers(this, _photo_extraInitializers), __runInitializers(this, _linkedinUrl_initializers, void 0));
        order = (__runInitializers(this, _linkedinUrl_extraInitializers), __runInitializers(this, _order_initializers, void 0));
        activityCount = (__runInitializers(this, _order_extraInitializers), __runInitializers(this, _activityCount_initializers, void 0));
        isActive = (__runInitializers(this, _activityCount_extraInitializers), __runInitializers(this, _isActive_initializers, void 0));
        constructor() {
            __runInitializers(this, _isActive_extraInitializers);
        }
    };
})();
export { CreateTeamMemberDto };
let UpdateTeamMemberDto = (() => {
    let _name_decorators;
    let _name_initializers = [];
    let _name_extraInitializers = [];
    let _role_decorators;
    let _role_initializers = [];
    let _role_extraInitializers = [];
    let _department_decorators;
    let _department_initializers = [];
    let _department_extraInitializers = [];
    let _departmentId_decorators;
    let _departmentId_initializers = [];
    let _departmentId_extraInitializers = [];
    let _email_decorators;
    let _email_initializers = [];
    let _email_extraInitializers = [];
    let _phone_decorators;
    let _phone_initializers = [];
    let _phone_extraInitializers = [];
    let _access_decorators;
    let _access_initializers = [];
    let _access_extraInitializers = [];
    let _status_decorators;
    let _status_initializers = [];
    let _status_extraInitializers = [];
    let _joinDate_decorators;
    let _joinDate_initializers = [];
    let _joinDate_extraInitializers = [];
    let _avatarInitials_decorators;
    let _avatarInitials_initializers = [];
    let _avatarInitials_extraInitializers = [];
    let _avatarColor_decorators;
    let _avatarColor_initializers = [];
    let _avatarColor_extraInitializers = [];
    let _bio_decorators;
    let _bio_initializers = [];
    let _bio_extraInitializers = [];
    let _photoUrl_decorators;
    let _photoUrl_initializers = [];
    let _photoUrl_extraInitializers = [];
    let _photo_decorators;
    let _photo_initializers = [];
    let _photo_extraInitializers = [];
    let _linkedinUrl_decorators;
    let _linkedinUrl_initializers = [];
    let _linkedinUrl_extraInitializers = [];
    let _order_decorators;
    let _order_initializers = [];
    let _order_extraInitializers = [];
    let _activityCount_decorators;
    let _activityCount_initializers = [];
    let _activityCount_extraInitializers = [];
    let _isActive_decorators;
    let _isActive_initializers = [];
    let _isActive_extraInitializers = [];
    return class UpdateTeamMemberDto {
        static {
            const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
            _name_decorators = [IsOptional(), IsString()];
            _role_decorators = [IsOptional(), IsString()];
            _department_decorators = [IsOptional(), IsString()];
            _departmentId_decorators = [IsOptional(), IsString()];
            _email_decorators = [IsOptional(), IsEmail({}, { message: 'Adresse email invalide' })];
            _phone_decorators = [IsOptional(), IsString()];
            _access_decorators = [IsOptional(), IsEnum(MemberAccess)];
            _status_decorators = [IsOptional(), IsEnum(MemberStatus)];
            _joinDate_decorators = [IsOptional(), IsDateString()];
            _avatarInitials_decorators = [IsOptional(), IsString()];
            _avatarColor_decorators = [IsOptional(), IsString()];
            _bio_decorators = [IsOptional(), IsString()];
            _photoUrl_decorators = [IsOptional(), IsString()];
            _photo_decorators = [IsOptional(), IsString()];
            _linkedinUrl_decorators = [IsOptional(), IsUrl({}, { message: 'URL LinkedIn invalide' })];
            _order_decorators = [IsOptional(), IsNumber()];
            _activityCount_decorators = [IsOptional(), IsNumber()];
            _isActive_decorators = [IsOptional(), IsBoolean()];
            __esDecorate(null, null, _name_decorators, { kind: "field", name: "name", static: false, private: false, access: { has: obj => "name" in obj, get: obj => obj.name, set: (obj, value) => { obj.name = value; } }, metadata: _metadata }, _name_initializers, _name_extraInitializers);
            __esDecorate(null, null, _role_decorators, { kind: "field", name: "role", static: false, private: false, access: { has: obj => "role" in obj, get: obj => obj.role, set: (obj, value) => { obj.role = value; } }, metadata: _metadata }, _role_initializers, _role_extraInitializers);
            __esDecorate(null, null, _department_decorators, { kind: "field", name: "department", static: false, private: false, access: { has: obj => "department" in obj, get: obj => obj.department, set: (obj, value) => { obj.department = value; } }, metadata: _metadata }, _department_initializers, _department_extraInitializers);
            __esDecorate(null, null, _departmentId_decorators, { kind: "field", name: "departmentId", static: false, private: false, access: { has: obj => "departmentId" in obj, get: obj => obj.departmentId, set: (obj, value) => { obj.departmentId = value; } }, metadata: _metadata }, _departmentId_initializers, _departmentId_extraInitializers);
            __esDecorate(null, null, _email_decorators, { kind: "field", name: "email", static: false, private: false, access: { has: obj => "email" in obj, get: obj => obj.email, set: (obj, value) => { obj.email = value; } }, metadata: _metadata }, _email_initializers, _email_extraInitializers);
            __esDecorate(null, null, _phone_decorators, { kind: "field", name: "phone", static: false, private: false, access: { has: obj => "phone" in obj, get: obj => obj.phone, set: (obj, value) => { obj.phone = value; } }, metadata: _metadata }, _phone_initializers, _phone_extraInitializers);
            __esDecorate(null, null, _access_decorators, { kind: "field", name: "access", static: false, private: false, access: { has: obj => "access" in obj, get: obj => obj.access, set: (obj, value) => { obj.access = value; } }, metadata: _metadata }, _access_initializers, _access_extraInitializers);
            __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: obj => "status" in obj, get: obj => obj.status, set: (obj, value) => { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
            __esDecorate(null, null, _joinDate_decorators, { kind: "field", name: "joinDate", static: false, private: false, access: { has: obj => "joinDate" in obj, get: obj => obj.joinDate, set: (obj, value) => { obj.joinDate = value; } }, metadata: _metadata }, _joinDate_initializers, _joinDate_extraInitializers);
            __esDecorate(null, null, _avatarInitials_decorators, { kind: "field", name: "avatarInitials", static: false, private: false, access: { has: obj => "avatarInitials" in obj, get: obj => obj.avatarInitials, set: (obj, value) => { obj.avatarInitials = value; } }, metadata: _metadata }, _avatarInitials_initializers, _avatarInitials_extraInitializers);
            __esDecorate(null, null, _avatarColor_decorators, { kind: "field", name: "avatarColor", static: false, private: false, access: { has: obj => "avatarColor" in obj, get: obj => obj.avatarColor, set: (obj, value) => { obj.avatarColor = value; } }, metadata: _metadata }, _avatarColor_initializers, _avatarColor_extraInitializers);
            __esDecorate(null, null, _bio_decorators, { kind: "field", name: "bio", static: false, private: false, access: { has: obj => "bio" in obj, get: obj => obj.bio, set: (obj, value) => { obj.bio = value; } }, metadata: _metadata }, _bio_initializers, _bio_extraInitializers);
            __esDecorate(null, null, _photoUrl_decorators, { kind: "field", name: "photoUrl", static: false, private: false, access: { has: obj => "photoUrl" in obj, get: obj => obj.photoUrl, set: (obj, value) => { obj.photoUrl = value; } }, metadata: _metadata }, _photoUrl_initializers, _photoUrl_extraInitializers);
            __esDecorate(null, null, _photo_decorators, { kind: "field", name: "photo", static: false, private: false, access: { has: obj => "photo" in obj, get: obj => obj.photo, set: (obj, value) => { obj.photo = value; } }, metadata: _metadata }, _photo_initializers, _photo_extraInitializers);
            __esDecorate(null, null, _linkedinUrl_decorators, { kind: "field", name: "linkedinUrl", static: false, private: false, access: { has: obj => "linkedinUrl" in obj, get: obj => obj.linkedinUrl, set: (obj, value) => { obj.linkedinUrl = value; } }, metadata: _metadata }, _linkedinUrl_initializers, _linkedinUrl_extraInitializers);
            __esDecorate(null, null, _order_decorators, { kind: "field", name: "order", static: false, private: false, access: { has: obj => "order" in obj, get: obj => obj.order, set: (obj, value) => { obj.order = value; } }, metadata: _metadata }, _order_initializers, _order_extraInitializers);
            __esDecorate(null, null, _activityCount_decorators, { kind: "field", name: "activityCount", static: false, private: false, access: { has: obj => "activityCount" in obj, get: obj => obj.activityCount, set: (obj, value) => { obj.activityCount = value; } }, metadata: _metadata }, _activityCount_initializers, _activityCount_extraInitializers);
            __esDecorate(null, null, _isActive_decorators, { kind: "field", name: "isActive", static: false, private: false, access: { has: obj => "isActive" in obj, get: obj => obj.isActive, set: (obj, value) => { obj.isActive = value; } }, metadata: _metadata }, _isActive_initializers, _isActive_extraInitializers);
            if (_metadata) Object.defineProperty(this, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        }
        name = __runInitializers(this, _name_initializers, void 0);
        role = (__runInitializers(this, _name_extraInitializers), __runInitializers(this, _role_initializers, void 0));
        department = (__runInitializers(this, _role_extraInitializers), __runInitializers(this, _department_initializers, void 0));
        departmentId = (__runInitializers(this, _department_extraInitializers), __runInitializers(this, _departmentId_initializers, void 0));
        email = (__runInitializers(this, _departmentId_extraInitializers), __runInitializers(this, _email_initializers, void 0));
        phone = (__runInitializers(this, _email_extraInitializers), __runInitializers(this, _phone_initializers, void 0));
        access = (__runInitializers(this, _phone_extraInitializers), __runInitializers(this, _access_initializers, void 0));
        status = (__runInitializers(this, _access_extraInitializers), __runInitializers(this, _status_initializers, void 0));
        joinDate = (__runInitializers(this, _status_extraInitializers), __runInitializers(this, _joinDate_initializers, void 0));
        avatarInitials = (__runInitializers(this, _joinDate_extraInitializers), __runInitializers(this, _avatarInitials_initializers, void 0));
        avatarColor = (__runInitializers(this, _avatarInitials_extraInitializers), __runInitializers(this, _avatarColor_initializers, void 0));
        bio = (__runInitializers(this, _avatarColor_extraInitializers), __runInitializers(this, _bio_initializers, void 0));
        photoUrl = (__runInitializers(this, _bio_extraInitializers), __runInitializers(this, _photoUrl_initializers, void 0));
        photo = (__runInitializers(this, _photoUrl_extraInitializers), __runInitializers(this, _photo_initializers, void 0));
        linkedinUrl = (__runInitializers(this, _photo_extraInitializers), __runInitializers(this, _linkedinUrl_initializers, void 0));
        order = (__runInitializers(this, _linkedinUrl_extraInitializers), __runInitializers(this, _order_initializers, void 0));
        activityCount = (__runInitializers(this, _order_extraInitializers), __runInitializers(this, _activityCount_initializers, void 0));
        isActive = (__runInitializers(this, _activityCount_extraInitializers), __runInitializers(this, _isActive_initializers, void 0));
        constructor() {
            __runInitializers(this, _isActive_extraInitializers);
        }
    };
})();
export { UpdateTeamMemberDto };
